# Generated by Django 4.2.16 on 2025-03-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_client_arch_client_country_client_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bot_id',
        ),
        migrations.AddField(
            model_name='client',
            name='mac',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
