# Generated by Django 4.2.16 on 2025-03-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_remove_client_bot_id_client_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='ExecutionResult',
        ),
    ]
